### ISSUE TITLE
/our-jobs/ - on mobile, paragraph element line height

### ISSUE THREAD

**Issue by bFraley** [ainc/awesomeinc2013#11]
Paragraph text `line-height` for listings at https://awesomeinc.org/our-jobs is reduced and crowds lines together on mobile devices. I've reproduced this on Chrome, but is probably similar on other browsers.

The result is the same on larger screens when scaling browser window. The line-height is being reduced at this breakpoint  to 15px on line #181 in `custom.css` 

![ainc-moble-horiz](https://cloud.githubusercontent.com/assets/3700154/20456575/34f9d492-ae47-11e6-954f-8ec5cb73e4f4.jpg)

![01-css-console](https://cloud.githubusercontent.com/assets/3700154/20456591/82a1501c-ae47-11e6-9e79-b9af97db455f.png)

![02-css-console](https://cloud.githubusercontent.com/assets/3700154/20456604/c404d11e-ae47-11e6-8b3e-f9a6249384de.png)

**Comment by raney24** [comment]
Thanks for the heads up @bFraley!  Should be fixed now.

**Comment by bFraley** [comment]
looks great now @raney24
